// <auto-generated />
using System;
using Kids_Pocket_money.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kids_Pocket_money.Migrations
{
    [DbContext(typeof(ChoresContext))]
    [Migration("20250301122240_ChildrenTableAndSeed")]
    partial class ChildrenTableAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kids_Pocket_money.Entities.ChoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("Kids_Pocket_money.Models.ChildEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedPoints")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("ChildPoints")
                        .HasColumnType("int");

                    b.Property<int>("ChildScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pocketMoneySum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedPoints = 0,
                            Age = 15,
                            ChildPoints = 0,
                            ChildScore = 0,
                            Name = "Yiska",
                            pocketMoneySum = 0
                        },
                        new
                        {
                            Id = 2,
                            AddedPoints = 0,
                            Age = 13,
                            ChildPoints = 0,
                            ChildScore = 0,
                            Name = "Moriya",
                            pocketMoneySum = 0
                        },
                        new
                        {
                            Id = 3,
                            AddedPoints = 0,
                            Age = 11,
                            ChildPoints = 0,
                            ChildScore = 0,
                            Name = "Ariel",
                            pocketMoneySum = 0
                        },
                        new
                        {
                            Id = 4,
                            AddedPoints = 0,
                            Age = 4,
                            ChildPoints = 0,
                            ChildScore = 0,
                            Name = "Yoav",
                            pocketMoneySum = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
